version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
    volumes:
      - postgres:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - 8090:8090
  
  minio:
    image: minio/minio
    command: server /data --console-address ":9080"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - minio:/data
  lemonldap:
    image: coudot/lemonldap-ng
    ports:
      - 80:80
    environment:
      LOGLEVEL: debug
    volumes:
      - lemonldap-etc:/etc/lemonldap-ng
      - lemonldap-var:/var/lib/lemonldap-ng
volumes:
  minio: {}
  postgres: {}
  lemonldap-etc: {}
  lemonldap-var: {}
